### ISSUE TITLE
Where in this repo to put possible museum items? 

### ISSUE THREAD

**Issue by raiph** [perl6/museum-items#4]
* I'm assuming you (zoffix) are going to pick bits and bobs from this repo and turn it into a final museum presentation. So it likely doesn't much matter where we put stuff, and this issue I've opened is largely moot. If this is so, please confirm that, optionally ignore the rest of this issue, and close it.

* Based on "If you have any of these items, please submit them to the appropriate year directory" I thought the idea was to pick a year in which a significant event happened and add a page corresponding to that event to the appropriate year. But you've added a news posting about the mug throwing, which happened in 2000, to the 2002 directory, presumably because the news posting was dated 2002. Was that just a mistake / doesn't matter?

* I think most things span multiple years. Do you really want these posted in the multi year directory? For example, Apocalypse 1 has both a first published year and a span of years during which it was edited. Further, it's part of a group of Apocalypses that have an even larger span. And they're all part of a larger group of design documents that have an even larger span. Simplifying things, the Apocalypses and Exegeses were first published between 2001 and 2004, and the Synopses between 2004 and 2015. And edits continued thru 2017 I think. Anyhow, I've stuck the design documents item I added in multi year but perhaps it would have worked better to have created an A item and an E item in 2001 and a Synopses item in 2004? Conversely, I've stuck the Parrot item in 2001, because that's when the first release happened, but perhaps you'd have preferred that in multi-year? Does consistency matter ?

* AlexDaniel has opened an issue for "Interesting links" and I've added a comment/link to that thread. Would you much prefer we find an appropriate year (or "multi-year") to slot stuff into or is that perfectly fine too?

Thank you for all the things you do to (radically) improve P6's public face with projects like this.

**Comment by zoffixznet** [comment]
> I'm assuming you (zoffix) are going to pick bits and bobs from this repo and turn it into a final museum presentation

Yeah, that's the plan.

> But you've added a news posting about the mug throwing, which happened in 2000, to the 2002 directory, presumably because the news posting was dated 2002. Was that just a mistake / doesn't matter?

Yeah, I assumed it happened in 2002. Fixed https://github.com/perl6/museum-items/commit/18a9ff48e3

> I think most things span multiple years. Do you really want these posted in the multi year directory? 

Don't really know yet. In the final thing it'd probably be listed as "First Apocalypse is published $year" and description would go on to say that these were edited for so many years and so on. So based on that, it probably makes sense to place it into the $year dir. But some things I added I didn't really take a good look yet; they were just some links people tweeted at me.

> Would you much prefer we find an appropriate year

No idea. I guess either way is fine. I'm really more interested in having some content, and not worrying much about how people organize it right now.

**Comment by raiph** [comment]
Thanks.
